services:

  prometheus:
    image: prom/prometheus
    container_name: securecloud-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    container_name: securecloud-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  postgres:
    image: postgres:16
    container_name: securecloud-postgres
    restart: always
    environment:
      POSTGRES_DB: securecloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./app/database/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d securecloud"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./app/backend
    container_name: securecloud-backend
    restart: always
    environment:
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: securecloud
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./app/frontend
    container_name: securecloud-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data:

