name: Trivy Container Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t securecloud-devsecops-platform:latest .

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: securecloud-devsecops-platform:latest
          format: table
          exit-code: 0
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
